export const FETCH_BOOKING_DETAILS_REQUEST = 'FETCH_BOOKING_DETAILS_REQUEST';
export const FETCH_BOOKING_DETAILS_SUCCESS = "FETCH_BOOKING_DETAILS_SUCCESS";
export const FETCH_BOOKING_DETAILS_FAIL = "FETCH_BOOKING_DETAILS_FAIL";
export const ADD_BOOKING_DETAILS_SUCCESS = 'ADD_BOOKING_DETAILS_SUCCESS'
export const ADD_BOOKING_DETAILS_FAILURE = 'ADD_BOOKING_DETAILS_FAILURE'
export const UPDATE_BOOKING_DETAILS_SUCCESS = 'UPDATE_BOOKING_DETAILS_SUCCESS'
export const UPDATE_BOOKING_DETAILS_FAILURE = 'UPDATE_BOOKING_DETAILS_FAILURE'
export const DELETE_BOOKING_SUCCESS = 'DELETE_BOOKING_SUCCESS'
export const DELETE_BOOKING_FAILURE = 'DELETE_BOOKING_FAILURE'
export const FETCH_BOOKING_DETAILS_BY_USER_ID_SUCCESS = 'FETCH_BOOKING_DETAILS_BY_USER_ID_SUCCESS' 
export const FETCH_BOOKING_DETAILS_BY_USER_ID_FAIL = 'FETCH_BOOKING_DETAILS_BY_USER_ID_FAIL' 

